language: node_js
node_js:
  - "4.4.7"
install:
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm run coverage
  - codecov



